### ISSUE TITLE
Error in controller - Some datasets didn't produce anything

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#128] opened 2018-07-26 05:15 UTC
It seems that now we use a SRI template to fall back on in case our templates fail. Running our system on the seed datasets didn't produce results on the following three:

LL1_penn_fudan_pedestrian
LL0_186_braziltourism 
313_spectrometer

However, if we run 313_spectrometer independently for example, we are able to obtain output. The log file for the aws run for 313_spectrometer looks as follows

```
Namespace(configuration_file='/dsbox_efs/config/seed-41/partition-32/313_spectrometer/search_config.json', cpus=10, debug=False, output_prefix=None, timeout=55)
Using configuation:
{'cpus': 10,
 'dataset_schema': '/dsbox_efs/dataset/seed_datasets_current/313_spectrometer/313_spectrometer_dataset/datasetDoc.json',
 'executables_root': '/dsbox_efs/runs/seed/313_spectrometer/executables',
 'pipeline_logs_root': '/dsbox_efs/runs/seed/313_spectrometer/pipelines',
 'problem_root': '/dsbox_efs/dataset/seed_datasets_current/313_spectrometer/313_spectrometer_problem',
 'problem_schema': '/dsbox_efs/dataset/seed_datasets_current/313_spectrometer/313_spectrometer_problem/problemDoc.json',
 'temp_storage_root': '/dsbox_efs/runs/seed/313_spectrometer/supporting_files',
 'timeout': 55,
 'training_data_root': '/dsbox_efs/dataset/seed_datasets_current/313_spectrometer/313_spectrometer_dataset',
 'user_problems_root': '/dsbox_efs/runs/seed/313_spectrometer/user_problems'}
[INFO] No test data config found! Will split the data.
[INFO] - dsbox.controller.controller - Top level output directory: /dsbox_efs/runs/seed/313_spectrometer
[INFO] Template choices:
Template ' SRI_Mean_Baseline_Template ' has been added to template base.
Template ' random_forest_classification_template ' has been added to template base.
Template ' extra_trees_classification_template ' has been added to template base.
Template ' gradient_boosting_classification_template ' has been added to template base.
Template ' svc_classification_template ' has been added to template base.
Traceback (most recent call last):
  File "ta2-search", line 173, in <module>
    result = main(args)
  File "ta2-search", line 102, in main
    status = controller.train()
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/controller/controller.py", line 585, in train
    problem_info = self.problem_info, problem_loc = self.config['problem_schema'])
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/controller/controller.py", line 169, in split_dataset
    for train_index, test_index in sss.split(dataset[res_id], dataset[res_id].iloc[:, target_index]):
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 1204, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 1546, in _iter_indices
    raise ValueError("The least populated class in y has only 1"
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
```

**Comment by kyao** [comment] 2018-07-26 05:18
Duplicate issue?
https://github.com/usc-isi-i2/dsbox-ta2/issues/112
https://github.com/usc-isi-i2/dsbox-ta2/issues/124

**Comment by liangmuxin** [comment] 2018-07-26 17:17
I looked into LL0_186_braziltourism dataset. It is classification for multiclass, and the dataset is tiny and contain 7 classes, it is possible that we get too few type of classes when we split data.

**Comment by kyao** [comment] 2018-07-26 17:19
LL0_186_braziltourism problem is a duplicate of Issue #112, which is fixed.

**Comment by kyao** [comment] 2018-07-26 17:20
LL1_penn_fudan_pedestrian is duplicate of #124. 

I am closing this issue.

**Closed by kyao** 2018-07-26 17:20 UTC
Labels: bug
