### ISSUE TITLE
Add logging and debugging output

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#44] opened 2018-07-06 02:17 UTC
Use python's logging module to log the behavior our ta2 system and ta1 primitives.

Things to log include:

- Primitives executed in dsbox/template/runtime.py
- Metadata annotations add in profiler
- Columns add in featurizers

Debugging output:

- From each of the primitive output dataframes, save the first 50 rows in an output folder

**Comment by proska** [comment] 2018-07-07 00:06
@RqS I can see that you have added the logging for each step execution. The problem is we run multiple evaluations in parallel, hence the output is really cluttered. Is it possible to pack the logs of each evaluation into one log message? I am not if it is a reasonable thing to try, so just go with any solution that you find fit.

**Comment by szeke** [comment] 2018-07-07 00:11
How about using some string in the output to identify the process so that the logs can be parceled out by using grep

**Comment by RqS** [comment] 2018-07-07 01:34
@proska I have not added any logging, what you have seen is probably some print statements in profiler. But what you said is a problem, I also noticed when I am writing logging, will try to find some solution.

**Comment by kyao** [comment] 2018-07-07 01:42
The logging output is from the d3m primitive loading module. It prints a couple of lines for each primitive it loads.

I added an logger to controller.py and that caused d3m logs to to be printed.

**Comment by RqS** [comment] 2018-07-10 16:51
Merged

**Closed by RqS** 2018-07-10 16:51 UTC
